{% set version = "0.2.4" %}

package:
  name: klepto
  version: {{ version }}

source:
  url: https://github.com/uqfoundation/klepto/archive/klepto-{{ version }}.tar.gz
  sha256: 9664f4793e0b61962c9adf46454ff83a578a474aa5b17840af3a9d91ffe81283

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dill >=0.3.7
    - pox >=0.3.3

test:
  requires:
    - pytest
    # also test the optional dependencies
    - cloudpickle
    - h5py
    - jsonpickle
    - pandas
    - sqlalchemy
  imports:
    - klepto
    - klepto.archives
  commands:
    - python -m klepto.tests

about:
  home: https://github.com/uqfoundation/klepto
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: persistent caching to memory, disk, or database

  doc_url: http://klepto.rtfd.io/
  dev_url: https://github.com/uqfoundation/klepto

extra:
  recipe-maintainers:
    - h-vetinari
