{% set version = "0.2.3" %}

package:
  name: klepto
  version: {{ version }}

source:
  url: https://github.com/uqfoundation/klepto/archive/klepto-{{ version }}.tar.gz
  sha256: 5aaa85a9cf75d53031f40080aed3d6807789b909252dae7a6c1cb7bac8eb7939

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dill >=0.3.4
    - pox >=0.3.0

test:
  requires:
    - pytest
    # also test the optional dependencies
    - h5py
    - pandas
    - sqlalchemy
  imports:
    - klepto
    - klepto.archives
  commands:
    - python -m klepto.tests

about:
  home: https://github.com/uqfoundation/klepto
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: persistent caching to memory, disk, or database

  doc_url: http://klepto.rtfd.io/
  dev_url: https://github.com/uqfoundation/klepto

extra:
  recipe-maintainers:
    - h-vetinari
