{% set version = "0.2.5" %}

package:
  name: klepto
  version: {{ version }}

source:
  url: https://github.com/uqfoundation/klepto/archive/refs/tags/{{ version }}.tar.gz
  sha256: e805bcbcedc8ff7a6e6dbe59b5f4a6a2710d29464b2770a91bc5d4a189d879a3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dill >=0.3.8
    - pox >=0.3.4

test:
  requires:
    - pytest
    # also test the optional dependencies
    - cloudpickle
    - h5py
    - jsonpickle
    - pandas
    - sqlalchemy
  imports:
    - klepto
    - klepto.archives
  commands:
    - python -m klepto.tests

about:
  home: https://github.com/uqfoundation/klepto
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: persistent caching to memory, disk, or database

  doc_url: http://klepto.rtfd.io/
  dev_url: https://github.com/uqfoundation/klepto

extra:
  recipe-maintainers:
    - h-vetinari
